version: '3.1'

services:

  db:
#    build: ./.docker/db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"

  adminer:
    build: ./.docker/adminer
    restart: always
    ports:
      - 6080:8080
